### ISSUE TITLE
How to set batch_size properly in Landmark Regression Training？

### ISSUE THREAD

**Issue by kasakinozomi123** [mohsij/spacecraft-pose-estimation#1]
Hello author, when I tried to Train Adversarial Landmark Regression on a single NVIDIA RTX 3090 24 GB GPU, I had to lower the BATCH_SIZE_PER_GPU parameter in lit_hpc_001.yaml because of the problem: CUDA:out of memory, and when I set BATCH_SIZE_PER_GPU parameter : 2,  it was no longer out of memory, but another error was reported (as shown below), how can I solve it? Do I have to adjust other parameters when adjusting BATCH_SIZE?
Hope you can tell me how to solve this problem in your busy schedule sincerely！

the error in the terminal:

TRAIN:
  BATCH_SIZE_PER_GPU: 2
  BATCH_SIZE_PER_GPU_ADVERSARIAL_SET: 2
  BEGIN_EPOCH: 0
  CHECKPOINT: 
  END_EPOCH: 40
  GAMMA1: 0.99
  GAMMA2: 0.0
  LR: 0.001
  LR_FACTOR: 0.1
  LR_STEP: [25, 35]
  MOMENTUM: 0.9
  NESTEROV: False
  OPTIMIZER: adam
  RESUME: False
  SHUFFLE: True
  WD: 0.0001
WORKERS: 0
=> init weights from normal distribution
=> loading pretrained model models/pytorch/imagenet/hrnet_w32-36af842e.pth
=> load 47966 samples
=> load 6740 samples
=> load 11994 samples
=> load 6740 samples
/home/zhouzhiyi/anaconda3/envs/pep/lib/python3.8/site-packages/torch/nn/modules/loss.py:529: UserWarning: Using a target size (torch.Size([2, 589824])) that is different to the input size (torch.Size([2, 147456])). This will likely lead to incorrect results due to broadcasting. Please ensure they have the same size.
  return F.mse_loss(input, target, reduction=self.reduction)
Traceback (most recent call last):
  File "tools/train_da_ms.py", line 315, in <module>
    main()
  File "tools/train_da_ms.py", line 266, in main
    train_da_ms(cfg, train_loader, train_loader2, model, discriminator, criterion, criterion2, optimizer, optimizer2, 
  File "/home/zhouzhiyi/workspace/6D/spacecraft-pose-estimation-main/landmark_regression/tools/../lib/core/function.py", line 236, in train_da_ms
    hm_loss2 = criterion(output2, target2, target_weight2)
  File "/home/zhouzhiyi/anaconda3/envs/pep/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/zhouzhiyi/workspace/6D/spacecraft-pose-estimation-main/landmark_regression/tools/../lib/core/loss.py", line 37, in forward
    loss += 0.5 * self.criterion(heatmap_pred, heatmap_gt)
  File "/home/zhouzhiyi/anaconda3/envs/pep/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/zhouzhiyi/anaconda3/envs/pep/lib/python3.8/site-packages/torch/nn/modules/loss.py", line 529, in forward
    return F.mse_loss(input, target, reduction=self.reduction)
  File "/home/zhouzhiyi/anaconda3/envs/pep/lib/python3.8/site-packages/torch/nn/functional.py", line 3261, in mse_loss
    expanded_input, expanded_target = torch.broadcast_tensors(input, target)
  File "/home/zhouzhiyi/anaconda3/envs/pep/lib/python3.8/site-packages/torch/functional.py", line 75, in broadcast_tensors
    return _VF.broadcast_tensors(tensors)  # type: ignore[attr-defined]
RuntimeError: The size of tensor a (147456) must match the size of tensor b (589824) at non-singleton dimension 1

**Comment by mohsij** [comment]
Hi, thanks for opening the issue. I tested this code and an older version I have. This definitely looks like a bug. I'll investigate and commit the fix.

**Comment by mohsij** [comment]
This issue has been addressed in the latest merge to main. It wasn't due to the batch size rather because the lower scale heatmaps weren't being generated correctly in the code. You can use any batch size now. I have tested it.
